# This file is where you define your pipelines. You can define multiple.
# For more information on multiple pipelines, see the documentation:
#   https://www.elastic.co/guide/en/logstash/current/multiple-pipelines.html

- pipeline.id: intake
  queue.type: persisted
  path.config: "/usr/share/logstash/pipeline/intake.conf"

- pipeline.id: production
  queue.type: persisted
  path.config: "/usr/share/logstash/pipeline/production.conf"

- pipeline.id: development
  path.config: "/usr/share/logstash/pipeline/development.conf"
